//------------------------------------------------------------------------------
// <auto-generated>
//     Bu kod araç tarafından oluşturuldu.
//     Çalışma Zamanı Sürümü:4.0.30319.42000
//
//     Bu dosyada yapılacak değişiklikler yanlış davranışa neden olabilir ve
//     kod yeniden oluşturulursa kaybolur.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sonBingol.Kaynaklar {
    using System;
    
    
    /// <summary>
    ///   Yerelleştirilmiş dizeleri aramak gibi işlemler için, türü kesin olarak belirtilmiş kaynak sınıfı.
    /// </summary>
    // Bu sınıf ResGen veya Visual Studio gibi bir araç kullanılarak StronglyTypedResourceBuilder
    // sınıfı tarafından otomatik olarak oluşturuldu.
    // Üye eklemek veya kaldırmak için .ResX dosyanızı düzenleyin ve sonra da ResGen
    // komutunu /str seçeneğiyle yeniden çalıştırın veya VS projenizi yeniden oluşturun.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class lang {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal lang() {
        }
        
        /// <summary>
        ///   Bu sınıf tarafından kullanılan, önbelleğe alınmış ResourceManager örneğini döndürür.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("sonBingol.Kaynaklar.lang", typeof(lang).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Tümü için geçerli iş parçacığının CurrentUICulture özelliğini geçersiz kular
        ///   CurrentUICulture özelliğini tüm kaynak aramaları için geçersiz kılar.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Bingöle Hoşgeldiniz! benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string bingol {
            get {
                return ResourceManager.GetString("bingol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Doğal güzellikleri ve sıcak insanlarıyla Bingöl, sizleri unutulmaz bir deneyime davet ediyor. Karın bembeyaz örtüsüyle muhteşem manzaralar sunan kayak merkezlerinden, gökyüzüne açılan kapı gibi hissettiren Yüzen Adalar’a kadar pek çok keşfedilecek yer var. Tarih ve doğanın iç içe geçtiği bu şehirde, geleneksel lezzetleri tatmadan dönmeyin. Bingöl balının eşsiz tadı ve meşhur yöresel yemekleri, damaklarda unutulmaz bir iz bırakır. Ayrıca, Bingöl’ün misafirperver insanları, ziyaretinizi daha da anlamlı kılaca [dizenin kalan bölümü kesildi]&quot;; benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string metin {
            get {
                return ResourceManager.GetString("metin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   SON GİRİLEN YERLER benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string songirilenyerler {
            get {
                return ResourceManager.GetString("songirilenyerler", resourceCulture);
            }
        }
    }
}
